apiVersion: batch/v1
kind: Job
metadata:
  name: energize-job
  labels:
    app: energize
    kai.scheduler/queue: cisuc-regular
    scheduling.run.ai/queue-name: cisuc-regular
spec:
  template:
    metadata:
      labels:
        app: energize
        kai.scheduler/queue: cisuc-regular
        scheduling.run.ai/queue-name: cisuc-regular
    spec:
      restartPolicy: Never
      containers:
      - name: energize
        image: registry.ml-cluster.dei.uc.pt/library/energize:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            nvidia.com/gpu: "1"
          requests:
            nvidia.com/gpu: "1"
        volumeMounts:
        - name: config-volume
          mountPath: /home/config
          readOnly: true
        - name: experiments-volume
          mountPath: /home/experiments
        env:
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,utility"
        command: ["/bin/bash"]
        args:
        - "-c"
        - "nvidia-smi && ls -la /home && ls -la /home/example/ && ls -la /home/config/ && cat /home/config/example_config.json && /opt/conda/envs/energize/bin/python -u -m energize.main -d mnist -c /home/config/example_config.json -g /home/config/energize.grammar --run 0 --gpu-enabled"
      volumes:
      - name: config-volume
        configMap:
          name: energize-config
      - name: experiments-volume
        emptyDir: {}